services:
  - type: web
    name: chamaledger-api
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /api/v1/health/ping
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: chamaledger-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: chamaledger-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: chamaledger-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: chamaledger-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: chamaledger-db
          property: password
      - key: JWT_SECRET
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_CALLBACK_URL
        sync: false

databases:
  - name: chamaledger-db
    plan: free
    region: oregon
