server:
  port: ${PORT:8080}

spring:
  application:
    name: chamaledger

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chamaledger_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: false

# JWT
jwt:
  secret: ${JWT_SECRET:MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNA==}
  expiration: 86400000

# Third Party
app:
  brevo:
    api-key: ${BREVO_API_KEY}

  gemini:
    api-key: ${GEMINI_API_KEY}
    model-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

# M-Pesa
mpesa:
  consumer-key: ${MPESA_CONSUMER_KEY}
  consumer-secret: ${MPESA_CONSUMER_SECRET}
  grant-type: client_credentials
  auth-url: https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
  stk-push-url: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
  stk-query-url: https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query
  shortcode: "174379"
  passkey: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
  callback-url: ${MPESA_CALLBACK_URL}

logging:
  level:
    ke.co.chamaledger: DEBUG