spring:
  application:
    name: chamaledger

  datasource:
    url: jdbc:postgresql://localhost:5432/chamaledger_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNA==
  expiration: 86400000

# M-Pesa Daraja API Configuration
mpesa:
  consumer-key: ${MPESA_CONSUMER_KEY:your_actual_key_here}
  consumer-secret: ${MPESA_CONSUMER_SECRET:your_actual_secret_here}
  grant-type: client_credentials
  auth-url: https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
  stk-push-url: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
  stk-query-url: https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query
  # The Shortcode and Passkey come from your Test Credentials in Daraja
  shortcode: "174379"
  passkey: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
  callback-url: https://your-domain.com/api/v1/callback/mpesa